### ISSUE TITLE
您好,咨询一下请求的路径

### ISSUE THREAD

**Issue by easyatgithub** [CB-ysx/egg-ts-base#1]
项目配置好启动后 
 http://127.0.0.1:7001/show 
得到的是
{"payload":{},"code":404,"msg":"接口不存在或methods错误"}
代码里看不出其他内容，方便描述一下请求路径么

**Comment by charlieysx** [comment]
@easyatgithub 
我这边试了可以哦。
我是
1、clone项目
2、安装数据库表
3、npm i
4、npm run dev
5、打开http://127.0.0.1:7001/show

**Comment by Shhuy** [comment]
是Controller层路径装饰器传入的文件路径参数是有问题的。
例如你读取的路径是："F:\...\..\...\egg-ts-base\app\controller\example\test.ts" 这中反斜杠在装换的时候是会出错的，得到的前面拼接路径一直是 's' 
![image](https://user-images.githubusercontent.com/42715523/90018015-e6211680-dcde-11ea-8fd1-8d6f4ece4c32.png)
所以上边在获取路径的时候需要把反斜杠转换为斜杠就可以了。
![image](https://user-images.githubusercontent.com/42715523/90018111-04871200-dcdf-11ea-9763-caf27e531675.png)
@CB-ysx 是否可以看下是因为什么目前我是这样解决的
